version: "2"

issues:
  max-issues-per-linter: 0 # Maximum issues count per one linter.
  max-same-issues: 0 #Maximum count of issues with the same text.
  uniq-by-line: false # Make issues output unique by line.
  new: true
  new-from-merge-base: main
  new-from-rev: HEAD
  # Excluding configuration per-path, per-linter, per-text and per-source

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - containedctx
    - copyloopvar
    - cyclop
    - decorder
    - dupl
    - embeddedstructfieldcheck
    - errname
    - errorlint
    - exptostd
    - funcorder
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godoclint
    - godox
    - gosec
    - govet
    - iface
    - lll
    - maintidx
    - misspell
    - mnd
    - modernize
    - nestif
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unparam
    - unused
    - usetesting
    - whitespace
    - wsl_v5
    - errcheck
  settings:
    cyclop:
      # The maximal code complexity to report.
      # Default: 10
      max-complexity: 10
      # The maximal average package complexity.
      # If it's higher than 0.0 (float) the check is enabled.
      # Default: 0.0
      package-average: 0
    decorder:
      # Required order of `type`, `const`, `var` and `func` declarations inside a file.
      # Default: types before constants before variables before functions.
      dec-order:
        - type
        - const
        - var
        - func
      # If true, underscore vars (vars with "_" as the name) will be ignored at all checks.
      # Default: false (underscore vars are not ignored)
      ignore-underscore-vars: false
      # If true, order of declarations is not checked at all.
      # Default: true (disabled)
      disable-dec-order-check: false
      # If true, `init` func can be anywhere in file (does not have to be declared before all other functions).
      # Default: true (disabled)
      disable-init-func-first-check: false
      # If true, multiple global `type`, `const` and `var` declarations are allowed.
      # Default: true (disabled)
      disable-dec-num-check: false
      # If true, type declarations will be ignored for dec num check.
      # Default: false (type statements are not ignored)
      disable-type-dec-num-check: false
      # If true, const declarations will be ignored for dec num check.
      # Default: false (const statements are not ignored)
      disable-const-dec-num-check: false
      # If true, var declarations will be ignored for dec num check.
      # Default: false (var statements are not ignored)
      disable-var-dec-num-check: false
    lll:
      # Max line length, lines longer will be reported.
      # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
      # Default: 120.
      line-length: 120
      # Tab width in spaces.
      # Default: 1
      tab-width: 1
    nestif:
      # Minimal complexity of if statements to report.
      # Default: 5
      min-complexity: 4

formatters:
  enable:
    - gofmt
    - golines
    - goimports
    # - swaggo

  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"

    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120
      # Length of a tabulation.
      # Default: 4
      tab-len: 4
      # Shorten single-line comments.
      # Default: false
      shorten-comments: true
      # Default: true
      reformat-tags: false
      # Split chained methods on the dots as opposed to the arguments.
      # Default: true
      chain-split-dots: true

run:
  go: "1.25"
  timeout: 10m
